# Generated by Django 3.0.3 on 2020-03-04 04:36

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', mdeditor.fields.MDTextField()),
            ],
        ),
    ]
